version: 2

default: &defaults
  machine: true

jobs:
  build:
    <<: *defaults
    environment:
      VUE_PORT: 8080
      NGINX_PORT: 80
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Build docker containers
          command: docker-compose up -d --build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  lint:
    <<: *defaults
    environment:
      VUE_PORT: 8080
      NGINX_PORT: 80
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Build docker containers
          command: docker-compose up -d --build
      - run:
          name: Linting vue files
          command: docker-compose exec frontend yarn lint

workflows:
  version: 2
  build:
    jobs:
      - build
      - lint:
          requires:
            - build
